### ISSUE TITLE
Change Initial Position and embed youtube player in PiPViewController.

### ISSUE THREAD

**Issue by iamsanketray123** [Kofktu/PIPKit#1]
How do I set the initial position of the PiPView and also embed an YouTube player so that I can replicate the WhatsApp behavior ?

**Comment by Kofktu** [comment]
@iamsanketray123 
Add to InitialPosition Property in PIPUsable Protocol
this [PR](https://github.com/Kofktu/PIPKit/pull/2)  has been shipped with 0.1.0 release and will be available in CocoaPods soon 🎉

Youtube Player uses [YTPlayerView](https://developers.google.com/youtube/v3/guides/ios_youtube_helper) 
by creating and using a PIPViewController.
or
You can create your own YouTube player using AVPlayer/AVPlayerItem/AVPlayerLayer
That's what I've been using in my app [CLiOS](
https://itunes.apple.com/app/id1404129494?l=ko&ls=1&mt=8)

![simulator screen shot - iphone xs - 2019-01-26 at 10 09 13](https://user-images.githubusercontent.com/1860205/51780501-74ac6200-2152-11e9-849c-767f0c43c279.png)
