### ISSUE TITLE
On iOS 13, PIP doesn't appear over presented view controllers

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [Kofktu/PIPKit#10]
Firstly, thank you for this, this is amazing! 

I found when you present a view controller in iOS 13 it appears overtop the PIP window, unlike iOS 12. You can try out the example project to see the issue.

**Comment by gali8** [comment]
PIPKit not supports UIWindow.
I did PIPWKit that supports UIWindow and works with iOS 13 modal views.
https://github.com/nexor-it/PIPWKit

Yes it's inspired to PIPKit but is not a fork

**Comment by jordanhbuiltbyhq** [comment]
@gali8 It looks just like a fork but doesn't include any of the recent work put into this repo. Why not submit a PR here?

**Comment by gali8** [comment]
@jordanhbuiltbyhq it's not a fork. I mean, i started with this project (exactly on yesterday afternoon), but i changed a lot of code so can't be merged on PIPKit.

Anyway, what about "the recent work"? Are you talking about the develop branch?

**Comment by jordanhbuiltbyhq** [comment]
Yeah. You can still submit a PR with a lot of code changes I'm sure.

**Comment by Kofktu** [comment]
@gali8 
If there is anything to improve, let's send a PR to improve the project together.
The PIPWKit code has almost the same part. 
Why did you make a separate district and work?

**Comment by gali8** [comment]
@jordanhbuiltbyhq @Kofktu 
PIPKit is UIViewController based; PIPWKit is UIWindow based.

Both are in MIT. So what's the issue?

**Comment by Kofktu** [comment]
@gali8 
I'm not talking about code licensing issues,
for improvement, it means how to improve the project together.

**Comment by gali8** [comment]
@Kofktu I'm trying to explain you that a PR will "broke" your code. I know that looks like equal, but it isn't.
I'm not jealous :) so you can absolutely compare/copy what i wrote. At the same way, i can submit a PR but i think (imho) that will not be helpful for PIPKit.

**Comment by Kofktu** [comment]
@gali8 
Okay~ I understand
