### ISSUE TITLE
'PIPCorner' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by ishandini** [Kofktu/PIPKit#18]
Unable to modify the corner radius. This struct 'PIPCorner' need public init method.

**Comment by fukemy** [comment]
hi, did u fixed this? i saw PIPCorner were define as public but still get this error

**Comment by Kofktu** [comment]
Modify Access Control  [0.5.0](https://github.com/Kofktu/PIPKit/tree/0.5.0)
I'm sorry for being late.
