### ISSUE TITLE
show viewcontroller over pip controller

### ISSUE THREAD

**Issue by fukemy** [Kofktu/PIPKit#23]
hi, i want to show a view controller over pipController, but present not working, can u help

**Comment by Kofktu** [comment]
Please write down what kind of issue it is.
I think it could be helpful.

**Comment by fukemy** [comment]
hi, when I showing pip with state is minimizing, after presenter a view controller, this VC cover the pip

**Comment by Kofktu** [comment]
[1.0.0](https://github.com/Kofktu/PIPKit/tree/1.0.0) version that modified the issue has been distributed.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1860205/147902256-fbe283cf-04d3-4812-ae22-92348644a671.png">

**Comment by fukemy** [comment]
love u, can new feature AVPIPKitUsable work with webRTC. I want to display user call video like this. Thanks
