### ISSUE TITLE
PIP position is not correct

### ISSUE THREAD

**Issue by yatindma** [Kofktu/PIPKit#3]
I am using PIPKit for Video call in PIP mode but some part of the PIPView is going down the screen.

**Comment by yatindma** [comment]
We can' set initial pip position as per the code

**Comment by Kofktu** [comment]
```swift
public enum PIPPosition {
    case topLeft
    case middleLeft
    case bottomLeft
    case topRight
    case middleRight
    case bottomRight
}

public protocol PIPUsable {
    var initialPosition: PIPPosition { get }
}
```

PIPUsable Protocol's use initialPosition
[Example](https://github.com/Kofktu/PIPKit/blob/f77b8c707a5a961f3ace83df0be99318fae5f433/Example/Example/ViewController.swift#L70)

**Comment by yatindma** [comment]
Thanks a lot
