### ISSUE TITLE
more detail about AVPIPKitVideoController

### ISSUE THREAD

**Issue by fukemy** [Kofktu/PIPKit#30]
Hi, can u explain more about AVPIPKitVideoController, im trying to implement webRTC call and startPIP, but the result is only white screen. My targetView is mainRemoteView( to display caller video)

**Comment by Kofktu** [comment]
## Flow
AVPIPKitUsable.pipTargetView -> 
UIImage(VideoProvider) -> CMSampleBuffer(VideoProvider) -> BufferLayer(VideoProvider)
AVPictureInPictureController(w. BufferLayer) (VideoController)

can you check if the image(mainRemoteView -> UIImage) is valid?

**Comment by fukemy** [comment]
sorry if my knowledge is wrong. I saw u convert UIView -> UIImage -> CMSampleBuffer -> BufferLayer

```

        guard let buffer = targetView?.uiImage.cmSampleBuffer(preferredFramesPerSecond: preferredFramesPerSecond) else {
            return
        }
```

i am ensure my mainRemoteView is valid. here is more about my mainRemoteView
```

    @IBOutlet weak var mainRemoteView : WebRTCViewWithoutButton!
```

about WebrtcViewWithoutButton

```
final class WebRTCViewWithoutButton: UIView, RTCVideoViewDelegate {
    
    var videoView = RTCEAGLVideoView(frame: .zero)
    
```

mainRemoteView still displaying caller's video in fullScreen, but when enterPIP it's only show white screen

**Comment by Kofktu** [comment]
`AVPIPKitRenderer` You can make your own renderer and use it in v1.0.1
