### ISSUE TITLE
Update target iOS version for Xcode 14.3 compatibility

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [Kofktu/PIPKit#38]
PipKit targets iOS 8 which is older than the recommended version for Xcode 14.3. This causes a build error when integrated with CocoaPods:

> File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Can you update it to at least iOS 9? Thanks!

**Comment by Kofktu** [comment]
@jordanhbuiltbyhq 
I'm sorry for the late resolution of the issue
Modified to version 1.1.0.
