### ISSUE TITLE
Notification is coming in PIP Size only

### ISSUE THREAD

**Issue by yatindma** [Kofktu/PIPKit#4]
I am trying to play video in PIP Mode but the notification alert on top am getting is also coming of pip size only

**Comment by Kofktu** [comment]
hmm.. I don't understand...
Can u tell me more about the situtation with the screenshot?

**Comment by yatindma** [comment]
![IMG_69D8B4AEFD81-2](https://user-images.githubusercontent.com/38318831/60434757-89bb7e80-9c25-11e9-96e3-a666023861a7.jpeg)


Please see the screenshot

**Comment by yatindma** [comment]
![IMG_1214](https://user-images.githubusercontent.com/38318831/60435505-6265b100-9c27-11e9-8893-5178e9ed5d51.jpg)

**Comment by Kofktu** [comment]
How is Notification Alert view added?
Can you show me the code?

PIPKit's View is added application's keywindow

**Comment by yatindma** [comment]
if pip size is more notification width is also more

**Comment by yatindma** [comment]
if let vc = UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: UsersSegueConstant.main) as? vc {
  var p = vc as PIPKitViewController
  PIPKit.show(with: p)
}

For notification am using a framework.

**Comment by Kofktu** [comment]
Hmm,, u need to see how the Notification Alert View are added to superView

**Comment by yatindma** [comment]
In the pod, they were showing over VC, so that's why the problem was coming.
