### ISSUE TITLE
Error in Xcode 16 : ‘CALayerCornerCurve’ is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by ShawnHuangS** [Kofktu/PIPKit#41]
After updating to Xcode 16, I encountered the following error message (as shown in the image).

![截圖 2024-09-19 下午3 11 47](https://github.com/user-attachments/assets/508d0a9f-02b8-4f73-a1d0-49f5372df68f)

Will the package be updated again? Thank you!

**Comment by Kofktu** [comment]
@ShawnHuangS 
I'm sorry for the late resolution of the issue
Modified to version 1.1.0.
