### ISSUE TITLE
Can we reshape the pip view ?? 

### ISSUE THREAD

**Issue by yatindma** [Kofktu/PIPKit#5]
I like to use pip for a different purpose, I like to make rounded corners for pip View, Is it possible from PIPKit ??

**Comment by Kofktu** [comment]
Yeah~  
You can give the rounded corner to the PIPUsable Protocol conform view.

```swift
class PIPView: PIPUsable {
..

 function() {
  self.layer.cornerRadius = X
  self.clipToBouds = true
}
}
```

**Comment by yatindma** [comment]
Yes done :) Thanks a lot
